name: Build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*.yml'
      - '.github/workflows/build-remote.yml'
      - '.github/workflows/preview.yml'
      - '.github/workflows/pull-request.yml'
      - '.idea/copyright/*.xml'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'Jenkinsfile '
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Info
        id: release-info
        uses: GeyserMC/actions/previous-release@master
        with:
          data: ${{ vars.RELEASEACTION_PREVRELEASE }}

      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 21

      - name: Build Geyser
        run: ./gradlew build
        env:
          BUILD_NUMBER: ${{ steps.release-info.outputs.curentRelease }}
          
      - name: Archive Artifacts
        uses: GeyserMC/actions/upload-multi-artifact@master
        if: success()
        with:
          artifacts: |
            bootstrap/mod/fabric/build/libs/Geyser-Fabric.jar
            bootstrap/mod/neoforge/build/libs/Geyser-NeoForge.jar
            bootstrap/standalone/build/libs/Geyser-Standalone.jar
            bootstrap/spigot/build/libs/Geyser-Spigot.jar
            bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar
            bootstrap/velocity/build/libs/Geyser-Velocity.jar
            bootstrap/viaproxy/build/libs/Geyser-ViaProxy.jar
